version: '3.7'

services:
    rest:
        build:
            context: ../rest
            dockerfile: Dockerfile
        environment:
            DEBUG: 1
        ports:
            - 5000:5000
        volumes:
            - ../rest:/app
        user: user
        command: sh -c "/app/run.sh > /app/container.log 2>&1"

    site:
        build:
            context: ../site
            dockerfile: Dockerfile
        environment:
            DEBUG: 1
            SITE_URL: http://site
            SITE_PORT: 8000
        ports:
            - 8000:8000
        volumes:
            - ../site:/app
        user: user
        command: sh -c "./run.sh > /app/container.log 2>&1"

    dev:
        build:
            context: ..
            dockerfile: Dockerfile
        environment:
            PYTHONPATH: /workspace/rest:/workspace/site
        volumes:
            - ..:/workspace
        user: user
        command: sleep infinity
