version: '3.7'

services:
    rest:
        build:
            context: ../rest
            dockerfile: Dockerfile
        environment:
            DEBUG: 1
            PYTHONPATH: /app/rest
        ports:
            - 5000:5000
        volumes:
            - ../rest:/app
        user: user
        command: /app/run.sh

    site:
        build:
            context: ../site
            dockerfile: Dockerfile
        environment:
            DEBUG: 1
        ports:
            - 8000:8000
        volumes:
            - ../site:/app
        user: user
        command: /app/run.sh

    dev:
        build:
            context: ..
            dockerfile: Dockerfile
        environment:
            PYTHONPATH: /workspace/rest:/workspace/site
        volumes:
            - ..:/workspace
        user: user
        command: sleep infinity
