version: '3.7'

services:
    rest:
        build:
            context: ../rest
            dockerfile: Dockerfile
        environment:
            DEBUG: 1
            PYTHONPATH: /workspace/rest
        ports:
            - 5000:5000
        volumes:
            - ..:/workspace
        user: user
        command: /workspace/rest/run.sh

    site:
        build:
            context: ../site
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - ..:/workspace
        user: user
        command: /workspace/site/run.sh

    dev:
        build:
            context: ..
            dockerfile: Dockerfile
        environment:
            PYTHONPATH: /workspace/rest
        volumes:
            - ..:/workspace
        user: user
        command: sleep infinity
